name: Create a new page
description: Submit a new page request for the Jekyll site.
title: "New Page: "
labels: ["new-page"]
body:
  - type: input
    id: page-title
    attributes:
      label: "Page Title"
      description: "Enter the title of the new page."
      placeholder: "Example: My New Blog Post"
    validations:
      required: true

  - type: textarea
    id: page-content
    attributes:
      label: "Page Content"
      description: "Enter the content for your new page."
      placeholder: "Write your page content here..."
    validations:
      required: true

  - type: input
    id: author
    attributes:
      label: "Author Name"
      description: "Enter your name."
      placeholder: "John Doe"
    validations:
      required: true
