name: New Page Request
description: Submit a new page to be added to the website
title: "[New Page]: "
labels: ["new-page"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to create a new page for our website!
  
  - type: input
    id: page_title
    attributes:
      label: Page Title
      description: The title of your page
      placeholder: Reboot ID 
    validations:
      required: true
  
  - type: dropdown
    id: page_layout
    attributes:
      label: Layout
      description: Choose the layout for your page
      options:
        - page
        - post
        - default
    validations:
      required: true
  
  - type: textarea
    id: page_content
    attributes:
      label: Page Content
      description: The content of your page (Markdown supported)
      placeholder: |
        ## Heading
        
        Your content here...
    validations:
      required: true
